title: Alexey Niktin
email: nikialeksey@gmail.com
description: >
  Blog about Java programming, clean code and Android development
baseurl: ""
url: "http://www.nikialeksey.com"
twitter_username: nikialeksey
github_username:  nikialeksey
google_analytics: UA-96573346-1
disqus:
    shortname: nikialeksey-blog

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
