title: Алексей Никитин
email: nikialeksey@gmail.com
description: >
  Блог про программирование на Java, чистый код и Android-разработку.
baseurl: ""
url: "http://www.nikialeksey.com"
twitter_username: nikialeksey
github_username:  nikialeksey

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
